spring.application.name=foodiesapi

#mongodb configuration
spring.data.mongodb.uri=mongodb://localhost:27017/test


#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-south-1
aws.s3.bucketname=foodfun-dishes

jwt.secret.key=q2NpY29sZSBzdGFja2V4Y2hhmdlaIahNKO9shsbLBabg==

#razorpay configuration
razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}